export interface Dialect {
  id: string
  name: string
  color: string
  region: string
}

export interface Word {
  id: string
  dialectId: string
  word: string
  translation: string
  pronunciation: string
  example: string
  exampleTranslation: string
  date: string
}

export const dialects: Dialect[] = [
  { id: "cebuano", name: "Cebuano", color: "oklch(0.55 0.2 260)", region: "Central Visayas" },
  { id: "ilocano", name: "Ilocano", color: "oklch(0.6 0.18 240)", region: "Northern Luzon" },
  { id: "hiligaynon", name: "Hiligaynon", color: "oklch(0.65 0.22 280)", region: "Western Visayas" },
  { id: "romblomanon", name: "Romblomanon", color: "oklch(0.5 0.2 220)", region: "Romblon Province" },
  { id: "kapampangan", name: "Kapampangan", color: "oklch(0.7 0.18 270)", region: "Central Luzon" },
  { id: "waray", name: "Waray", color: "oklch(0.58 0.2 250)", region: "Eastern Visayas" },
]

export const wordsDatabase: Word[] = [
  // --- CEBUANO ---
  {
    id: "1",
    dialectId: "cebuano",
    word: "Maayong buntag",
    translation: "Good morning",
    pronunciation: "mah-ah-yong boon-tahg",
    example: "Maayong buntag sa tanan!",
    exampleTranslation: "Good morning to everyone!",
    date: "2025-01-01",
  },
  {
    id: "2",
    dialectId: "cebuano",
    word: "Salamat",
    translation: "Thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat sa imong tabang.",
    exampleTranslation: "Thank you for your help.",
    date: "2025-01-02",
  },

  // --- ILOCANO ---
  {
    id: "3",
    dialectId: "ilocano",
    word: "Naimbag nga aldaw",
    translation: "Good day",
    pronunciation: "nah-eem-bahg ngah ahl-dahw",
    example: "Naimbag nga aldaw kenka!",
    exampleTranslation: "Good day to you!",
    date: "2025-01-03",
  },
  {
    id: "4",
    dialectId: "ilocano",
    word: "Agyamanak",
    translation: "Thank you",
    pronunciation: "ahg-yah-mah-nahk",
    example: "Agyamanak unay!",
    exampleTranslation: "Thank you very much!",
    date: "2025-01-04",
  },

  // --- HILIGAYNON ---
  {
    id: "5",
    dialectId: "hiligaynon",
    word: "Maayong aga",
    translation: "Good morning",
    pronunciation: "mah-ah-yong ah-gah",
    example: "Maayong aga sa inyo!",
    exampleTranslation: "Good morning to you!",
    date: "2025-01-05",
  },
  {
    id: "6",
    dialectId: "hiligaynon",
    word: "Salamat",
    translation: "Thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat gid!",
    exampleTranslation: "Thank you very much!",
    date: "2025-01-06",
  },

  // --- ROMBLOMANON ---
  {
    id: "7",
    dialectId: "romblomanon",
    word: "kamusta",
    translation: "hello",
    pronunciation: "kah-moos-tah",
    example: "Kamusta ka?",
    exampleTranslation: "How are you?",
    date: "2025-01-07",
  },
  {
    id: "8",
    dialectId: "romblomanon",
    word: "maayo nga aga",
    translation: "good morning",
    pronunciation: "mah-ah-yo ngah ah-gah",
    example: "Maayo nga aga sa imo!",
    exampleTranslation: "Good morning to you!",
    date: "2025-01-08",
  },
  {
    id: "13",
    dialectId: "romblomanon",
    word: "maayo nga hapon",
    translation: "good afternoon",
    pronunciation: "mah-ah-yo ngah hah-pon",
    example: "Maayo nga hapon!",
    exampleTranslation: "Good afternoon!",
    date: "2025-01-13",
  },
  {
    id: "14",
    dialectId: "romblomanon",
    word: "maayo nga gabi-i",
    translation: "good evening",
    pronunciation: "mah-ah-yo ngah gah-bee",
    example: "Maayo nga gabi-i sa tanan!",
    exampleTranslation: "Good evening to everyone!",
    date: "2025-01-14",
  },
  {
    id: "15",
    dialectId: "romblomanon",
    word: "maayo nga gab-i",
    translation: "good night",
    pronunciation: "mah-ah-yo ngah gahb-ee",
    example: "Maayo nga gab-i!",
    exampleTranslation: "Good night!",
    date: "2025-01-15",
  },
  {
    id: "16",
    dialectId: "romblomanon",
    word: "salamat",
    translation: "thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat ha imo.",
    exampleTranslation: "Thank you to you.",
    date: "2025-01-16",
  },
  {
    id: "17",
    dialectId: "romblomanon",
    word: "way sapayan",
    translation: "you're welcome",
    pronunciation: "why sah-pah-yahn",
    example: "Way sapayan!",
    exampleTranslation: "You're welcome!",
    date: "2025-01-17",
  },
  {
    id: "18",
    dialectId: "romblomanon",
    word: "hoo",
    translation: "yes",
    pronunciation: "hoh",
    example: "Hoo, tama ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-01-18",
  },
  {
    id: "19",
    dialectId: "romblomanon",
    word: "indi",
    translation: "no",
    pronunciation: "in-dee",
    example: "Indi, diri ko gusto.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-01-19",
  },
  {
    id: "20",
    dialectId: "romblomanon",
    word: "palihog",
    translation: "please",
    pronunciation: "pah-lee-hog",
    example: "Palihog, tabang ko.",
    exampleTranslation: "Please, help me.",
    date: "2025-01-20",
  },
  {
    id: "21",
    dialectId: "romblomanon",
    word: "pasensya",
    translation: "excuse me",
    pronunciation: "pah-sen-syah",
    example: "Pasensya, pwede ko maagi?",
    exampleTranslation: "Excuse me, can I pass?",
    date: "2025-01-21",
  },
  {
    id: "22",
    dialectId: "romblomanon",
    word: "pasaylo-a",
    translation: "sorry",
    pronunciation: "pah-sigh-loh-ah",
    example: "Pasaylo-a ko.",
    exampleTranslation: "I'm sorry.",
    date: "2025-01-22",
  },
  {
    id: "23",
    dialectId: "romblomanon",
    word: "ano",
    translation: "what",
    pronunciation: "ah-no",
    example: "Ano ini?",
    exampleTranslation: "What is this?",
    date: "2025-01-23",
  },
  {
    id: "24",
    dialectId: "romblomanon",
    word: "sino",
    translation: "who",
    pronunciation: "see-no",
    example: "Sino ka?",
    exampleTranslation: "Who are you?",
    date: "2025-01-24",
  },
  {
    id: "25",
    dialectId: "romblomanon",
    word: "diin",
    translation: "where",
    pronunciation: "dee-in",
    example: "Diin ka naghalin?",
    exampleTranslation: "Where are you from?",
    date: "2025-01-25",
  },
  {
    id: "26",
    dialectId: "romblomanon",
    word: "san-o",
    translation: "when",
    pronunciation: "sahn-oh",
    example: "San-o ka mag-abot?",
    exampleTranslation: "When will you arrive?",
    date: "2025-01-26",
  },
  {
    id: "27",
    dialectId: "romblomanon",
    word: "ngaa",
    translation: "why",
    pronunciation: "ngah-ah",
    example: "Ngaa ka naghibi?",
    exampleTranslation: "Why are you crying?",
    date: "2025-01-27",
  },
  {
    id: "28",
    dialectId: "romblomanon",
    word: "paano",
    translation: "how",
    pronunciation: "pah-ah-no",
    example: "Paano ini?",
    exampleTranslation: "How is this?",
    date: "2025-01-28",
  },
  {
    id: "29",
    dialectId: "romblomanon",
    word: "layaki",
    translation: "man",
    pronunciation: "lah-yah-kee",
    example: "Layaki siya.",
    exampleTranslation: "He is a man.",
    date: "2025-01-29",
  },
  {
    id: "30",
    dialectId: "romblomanon",
    word: "babayi",
    translation: "woman",
    pronunciation: "bah-bah-yee",
    example: "Babayi siya.",
    exampleTranslation: "She is a woman.",
    date: "2025-01-30",
  },
  {
    id: "31",
    dialectId: "romblomanon",
    word: "bata",
    translation: "child",
    pronunciation: "bah-tah",
    example: "Bata pa siya.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-01-31",
  },
  {
    id: "32",
    dialectId: "romblomanon",
    word: "amâ",
    translation: "father",
    pronunciation: "ah-mah",
    example: "Amâ ko siya.",
    exampleTranslation: "He is my father.",
    date: "2025-02-01",
  },
  {
    id: "33",
    dialectId: "romblomanon",
    word: "ina",
    translation: "mother",
    pronunciation: "ee-nah",
    example: "Ina ko siya.",
    exampleTranslation: "She is my mother.",
    date: "2025-02-02",
  },
  {
    id: "34",
    dialectId: "romblomanon",
    word: "utod nga layaki",
    translation: "brother",
    pronunciation: "oo-tod ngah lah-yah-kee",
    example: "Utod ko nga layaki siya.",
    exampleTranslation: "He is my brother.",
    date: "2025-02-03",
  },
  {
    id: "35",
    dialectId: "romblomanon",
    word: "utod nga babayi",
    translation: "sister",
    pronunciation: "oo-tod ngah bah-bah-yee",
    example: "Utod ko nga babayi siya.",
    exampleTranslation: "She is my sister.",
    date: "2025-02-04",
  },
  {
    id: "36",
    dialectId: "romblomanon",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilya ko sila.",
    exampleTranslation: "They are my family.",
    date: "2025-02-05",
  },
  {
    id: "37",
    dialectId: "romblomanon",
    word: "abyan",
    translation: "friend",
    pronunciation: "ahb-yahn",
    example: "Abyan ko siya.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-02-06",
  },
  {
    id: "38",
    dialectId: "romblomanon",
    word: "balay",
    translation: "house",
    pronunciation: "bah-lie",
    example: "Balay ko ini.",
    exampleTranslation: "This is my house.",
    date: "2025-02-07",
  },
  {
    id: "39",
    dialectId: "romblomanon",
    word: "eskwelahan",
    translation: "school",
    pronunciation: "es-kweh-lah-hahn",
    example: "Nag-eskwela ako sa eskwelahan.",
    exampleTranslation: "I study at school.",
    date: "2025-02-08",
  },
  {
    id: "40",
    dialectId: "romblomanon",
    word: "simbahan",
    translation: "church",
    pronunciation: "seem-bah-hahn",
    example: "Nag-simba kami sa simbahan.",
    exampleTranslation: "We go to church.",
    date: "2025-02-09",
  },
  {
    id: "41",
    dialectId: "romblomanon",
    word: "merkado",
    translation: "market",
    pronunciation: "mer-kah-doh",
    example: "Nag-bakal kami sa merkado.",
    exampleTranslation: "We shop at the market.",
    date: "2025-02-10",
  },
  {
    id: "42",
    dialectId: "romblomanon",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Nag-lakaw kami sa dalan.",
    exampleTranslation: "We walk on the road.",
    date: "2025-02-11",
  },
  {
    id: "43",
    dialectId: "romblomanon",
    word: "dagat",
    translation: "sea",
    pronunciation: "dah-gaht",
    example: "Nag-langoy kami sa dagat.",
    exampleTranslation: "We swim in the sea.",
    date: "2025-02-12",
  },
  {
    id: "44",
    dialectId: "romblomanon",
    word: "bukid",
    translation: "mountain",
    pronunciation: "boo-keed",
    example: "Nag-saka kami sa bukid.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-02-13",
  },
  {
    id: "45",
    dialectId: "romblomanon",
    word: "suba",
    translation: "river",
    pronunciation: "soo-bah",
    example: "Nag-langoy kami sa suba.",
    exampleTranslation: "We swim in the river.",
    date: "2025-02-14",
  },
  {
    id: "46",
    dialectId: "romblomanon",
    word: "adlaw",
    translation: "sun",
    pronunciation: "ahd-lahw",
    example: "Init ang adlaw.",
    exampleTranslation: "The sun is hot.",
    date: "2025-02-15",
  },
  {
    id: "47",
    dialectId: "romblomanon",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Hayag ang bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-02-16",
  },
  {
    id: "48",
    dialectId: "romblomanon",
    word: "bitoon",
    translation: "star",
    pronunciation: "bee-toh-on",
    example: "Damo nga bitoon sa langit.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-02-17",
  },
  {
    id: "49",
    dialectId: "romblomanon",
    word: "uran",
    translation: "rain",
    pronunciation: "oo-rahn",
    example: "Nag-uran karon.",
    exampleTranslation: "It's raining now.",
    date: "2025-02-18",
  },
  {
    id: "50",
    dialectId: "romblomanon",
    word: "hangin",
    translation: "wind",
    pronunciation: "hah-ngin",
    example: "Kusog ang hangin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-02-19",
  },
  {
    id: "51",
    dialectId: "romblomanon",
    word: "kalayo",
    translation: "fire",
    pronunciation: "kah-lah-yo",
    example: "Init ang kalayo.",
    exampleTranslation: "The fire is hot.",
    date: "2025-02-20",
  },
  {
    id: "52",
    dialectId: "romblomanon",
    word: "tubig",
    translation: "water",
    pronunciation: "too-big",
    example: "Bugnaw ang tubig.",
    exampleTranslation: "The water is cold.",
    date: "2025-02-21",
  },
  {
    id: "53",
    dialectId: "romblomanon",
    word: "kan-on",
    translation: "food",
    pronunciation: "kahn-on",
    example: "Nag-kaon kami.",
    exampleTranslation: "We are eating.",
    date: "2025-02-22",
  },
  {
    id: "54",
    dialectId: "romblomanon",
    word: "bugas",
    translation: "rice",
    pronunciation: "boo-gahs",
    example: "Nag-luto kami sang bugas.",
    exampleTranslation: "We cooked rice.",
    date: "2025-02-23",
  },
  {
    id: "55",
    dialectId: "romblomanon",
    word: "isdâ",
    translation: "fish",
    pronunciation: "ees-dah",
    example: "Nag-bakal kami sang isdâ.",
    exampleTranslation: "We bought fish.",
    date: "2025-02-24",
  },
  {
    id: "56",
    dialectId: "romblomanon",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Nag-luto kami sang karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-02-25",
  },
  {
    id: "57",
    dialectId: "romblomanon",
    word: "utan",
    translation: "vegetable",
    pronunciation: "oo-tahn",
    example: "Nag-kaon kami sang utan.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-02-26",
  },
  {
    id: "58",
    dialectId: "romblomanon",
    word: "prutas",
    translation: "fruit",
    pronunciation: "proo-tahs",
    example: "Nag-kaon kami sang prutas.",
    exampleTranslation: "We ate fruit.",
    date: "2025-02-27",
  },
  {
    id: "59",
    dialectId: "romblomanon",
    word: "ido",
    translation: "dog",
    pronunciation: "ee-doh",
    example: "May ido kami.",
    exampleTranslation: "We have a dog.",
    date: "2025-02-28",
  },
  {
    id: "60",
    dialectId: "romblomanon",
    word: "kuring",
    translation: "cat",
    pronunciation: "koo-ring",
    example: "May kuring kami.",
    exampleTranslation: "We have a cat.",
    date: "2025-03-01",
  },

  // --- KAPAMPANGAN ---
  {
    id: "9",
    dialectId: "kapampangan",
    word: "Mayap a abak",
    translation: "Good morning",
    pronunciation: "mah-yahp ah ah-bahk",
    example: "Mayap a abak kekayu!",
    exampleTranslation: "Good morning to you all!",
    date: "2025-01-09",
  },
  {
    id: "10",
    dialectId: "kapampangan",
    word: "Salamat",
    translation: "Thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat pu!",
    exampleTranslation: "Thank you (respectful)!",
    date: "2025-01-10",
  },

  // --- WARAY ---
  {
    id: "11",
    dialectId: "waray",
    word: "Maupay nga aga",
    translation: "Good morning",
    pronunciation: "mah-oo-pie ngah ah-gah",
    example: "Maupay nga aga ha iyo!",
    exampleTranslation: "Good morning to you!",
    date: "2025-01-11",
  },
  {
    id: "12",
    dialectId: "waray",
    word: "Salamat",
    translation: "Thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat hin damo!",
    exampleTranslation: "Thank you very much!",
    date: "2025-01-12",
  },

  // --- CEBUANO (CONTINUED) ---
  {
    id: "61",
    dialectId: "cebuano",
    word: "kumusta",
    translation: "hello",
    pronunciation: "koo-mus-tah",
    example: "Kumusta ka?",
    exampleTranslation: "How are you?",
    date: "2025-03-02",
  },
  {
    id: "62",
    dialectId: "cebuano",
    word: "maayong buntag",
    translation: "good morning",
    pronunciation: "mah-ah-yong boon-tahg",
    example: "Maayong buntag!",
    exampleTranslation: "Good morning!",
    date: "2025-03-03",
  },
  {
    id: "63",
    dialectId: "cebuano",
    word: "maayong hapon",
    translation: "good afternoon",
    pronunciation: "mah-ah-yong hah-pon",
    example: "Maayong hapon sa inyo!",
    exampleTranslation: "Good afternoon to you!",
    date: "2025-03-04",
  },
  {
    id: "64",
    dialectId: "cebuano",
    word: "maayong gabii",
    translation: "good evening",
    pronunciation: "mah-ah-yong gah-bee",
    example: "Maayong gabii!",
    exampleTranslation: "Good evening!",
    date: "2025-03-05",
  },
  {
    id: "65",
    dialectId: "cebuano",
    word: "maayong gabi-i",
    translation: "good night",
    pronunciation: "mah-ah-yong gah-bee-ee",
    example: "Maayong gabi-i!",
    exampleTranslation: "Good night!",
    date: "2025-03-06",
  },
  {
    id: "66",
    dialectId: "cebuano",
    word: "walay sapayan",
    translation: "you're welcome",
    pronunciation: "wah-lie sah-pah-yahn",
    example: "Walay sapayan!",
    exampleTranslation: "You're welcome!",
    date: "2025-03-07",
  },
  {
    id: "67",
    dialectId: "cebuano",
    word: "oo",
    translation: "yes",
    pronunciation: "oh",
    example: "Oo, tama ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-03-08",
  },
  {
    id: "68",
    dialectId: "cebuano",
    word: "dili",
    translation: "no",
    pronunciation: "dee-lee",
    example: "Dili, ayaw ko.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-03-09",
  },
  {
    id: "69",
    dialectId: "cebuano",
    word: "palihug",
    translation: "please",
    pronunciation: "pah-lee-hoog",
    example: "Palihug, tabang ko.",
    exampleTranslation: "Please, help me.",
    date: "2025-03-10",
  },
  {
    id: "70",
    dialectId: "cebuano",
    word: "pasayloa ko",
    translation: "excuse me",
    pronunciation: "pah-sigh-loh-ah ko",
    example: "Pasayloa ko, pwede ko maagi?",
    exampleTranslation: "Excuse me, can I pass?",
    date: "2025-03-11",
  },
  {
    id: "71",
    dialectId: "cebuano",
    word: "unsa",
    translation: "what",
    pronunciation: "oon-sah",
    example: "Unsa kini?",
    exampleTranslation: "What is this?",
    date: "2025-03-12",
  },
  {
    id: "72",
    dialectId: "cebuano",
    word: "kinsa",
    translation: "who",
    pronunciation: "kin-sah",
    example: "Kinsa ka?",
    exampleTranslation: "Who are you?",
    date: "2025-03-13",
  },
  {
    id: "73",
    dialectId: "cebuano",
    word: "asa",
    translation: "where",
    pronunciation: "ah-sah",
    example: "Asa ka gikan?",
    exampleTranslation: "Where are you from?",
    date: "2025-03-14",
  },
  {
    id: "74",
    dialectId: "cebuano",
    word: "kanus-a",
    translation: "when",
    pronunciation: "kah-noos-ah",
    example: "Kanus-a ka mag-abot?",
    exampleTranslation: "When will you arrive?",
    date: "2025-03-15",
  },
  {
    id: "75",
    dialectId: "cebuano",
    word: "ngano",
    translation: "why",
    pronunciation: "ngah-no",
    example: "Ngano ka naghilak?",
    exampleTranslation: "Why are you crying?",
    date: "2025-03-16",
  },
  {
    id: "76",
    dialectId: "cebuano",
    word: "unsaon",
    translation: "how",
    pronunciation: "oon-sah-on",
    example: "Unsaon kini?",
    exampleTranslation: "How is this?",
    date: "2025-03-17",
  },
  {
    id: "77",
    dialectId: "cebuano",
    word: "lalaki",
    translation: "man",
    pronunciation: "lah-lah-kee",
    example: "Lalaki siya.",
    exampleTranslation: "He is a man.",
    date: "2025-03-18",
  },
  {
    id: "78",
    dialectId: "cebuano",
    word: "babae",
    translation: "woman",
    pronunciation: "bah-bah-eh",
    example: "Babae siya.",
    exampleTranslation: "She is a woman.",
    date: "2025-03-19",
  },
  {
    id: "79",
    dialectId: "cebuano",
    word: "bata",
    translation: "child",
    pronunciation: "bah-tah",
    example: "Bata pa siya.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-03-20",
  },
  {
    id: "80",
    dialectId: "cebuano",
    word: "amahan",
    translation: "father",
    pronunciation: "ah-mah-hahn",
    example: "Amahan ko siya.",
    exampleTranslation: "He is my father.",
    date: "2025-03-21",
  },
  {
    id: "81",
    dialectId: "cebuano",
    word: "inahan",
    translation: "mother",
    pronunciation: "ee-nah-hahn",
    example: "Inahan ko siya.",
    exampleTranslation: "She is my mother.",
    date: "2025-03-22",
  },
  {
    id: "82",
    dialectId: "cebuano",
    word: "igsoon nga lalaki",
    translation: "brother",
    pronunciation: "ig-soon ngah lah-lah-kee",
    example: "Igsoon ko nga lalaki siya.",
    exampleTranslation: "He is my brother.",
    date: "2025-03-23",
  },
  {
    id: "83",
    dialectId: "cebuano",
    word: "igsoon nga babae",
    translation: "sister",
    pronunciation: "ig-soon ngah bah-bah-eh",
    example: "Igsoon ko nga babae siya.",
    exampleTranslation: "She is my sister.",
    date: "2025-03-24",
  },
  {
    id: "84",
    dialectId: "cebuano",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilya ko sila.",
    exampleTranslation: "They are my family.",
    date: "2025-03-25",
  },
  {
    id: "85",
    dialectId: "cebuano",
    word: "higala",
    translation: "friend",
    pronunciation: "hee-gah-lah",
    example: "Higala nako siya.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-03-26",
  },
  {
    id: "86",
    dialectId: "cebuano",
    word: "balay",
    translation: "house",
    pronunciation: "bah-lie",
    example: "Ako ning balay.",
    exampleTranslation: "This is my house.",
    date: "2025-03-27",
  },
  {
    id: "87",
    dialectId: "cebuano",
    word: "eskwelahan",
    translation: "school",
    pronunciation: "es-kweh-lah-hahn",
    example: "Nag-eskwela ko sa eskwelahan.",
    exampleTranslation: "I study at school.",
    date: "2025-03-28",
  },
  {
    id: "88",
    dialectId: "cebuano",
    word: "simbahan",
    translation: "church",
    pronunciation: "seem-bah-hahn",
    example: "Nagsimba kami sa simbahan.",
    exampleTranslation: "We go to church.",
    date: "2025-03-29",
  },
  {
    id: "89",
    dialectId: "cebuano",
    word: "merkado",
    translation: "market",
    pronunciation: "mer-kah-doh",
    example: "Namalit kami sa merkado.",
    exampleTranslation: "We shop at the market.",
    date: "2025-03-30",
  },
  {
    id: "90",
    dialectId: "cebuano",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Naglakaw kami sa dalan.",
    exampleTranslation: "We walk on the road.",
    date: "2025-03-31",
  },
  {
    id: "91",
    dialectId: "cebuano",
    word: "dagat",
    translation: "sea",
    pronunciation: "dah-gaht",
    example: "Naligo kami sa dagat.",
    exampleTranslation: "We swim in the sea.",
    date: "2025-04-01",
  },
  {
    id: "92",
    dialectId: "cebuano",
    word: "bukid",
    translation: "mountain",
    pronunciation: "boo-keed",
    example: "Nikatkat kami sa bukid.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-04-02",
  },
  {
    id: "93",
    dialectId: "cebuano",
    word: "sapa",
    translation: "river",
    pronunciation: "sah-pah",
    example: "Naligo kami sa sapa.",
    exampleTranslation: "We swim in the river.",
    date: "2025-04-03",
  },
  {
    id: "94",
    dialectId: "cebuano",
    word: "adlaw",
    translation: "sun",
    pronunciation: "ahd-lahw",
    example: "Init ang adlaw.",
    exampleTranslation: "The sun is hot.",
    date: "2025-04-04",
  },
  {
    id: "95",
    dialectId: "cebuano",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Hayag ang bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-04-05",
  },
  {
    id: "96",
    dialectId: "cebuano",
    word: "bituon",
    translation: "star",
    pronunciation: "bee-too-on",
    example: "Daghan og bituon sa langit.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-04-06",
  },
  {
    id: "97",
    dialectId: "cebuano",
    word: "ulan",
    translation: "rain",
    pronunciation: "oo-lahn",
    example: "Nag-ulan gahapon.",
    exampleTranslation: "It rained yesterday.",
    date: "2025-04-07",
  },
  {
    id: "98",
    dialectId: "cebuano",
    word: "hangin",
    translation: "wind",
    pronunciation: "hah-ngin",
    example: "Kusog ang hangin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-04-08",
  },
  {
    id: "99",
    dialectId: "cebuano",
    word: "kalayo",
    translation: "fire",
    pronunciation: "kah-lah-yo",
    example: "Init ang kalayo.",
    exampleTranslation: "The fire is hot.",
    date: "2025-04-09",
  },
  {
    id: "100",
    dialectId: "cebuano",
    word: "tubig",
    translation: "water",
    pronunciation: "too-big",
    example: "Bugnaw ang tubig.",
    exampleTranslation: "The water is cold.",
    date: "2025-04-10",
  },
  {
    id: "101",
    dialectId: "cebuano",
    word: "pagkaon",
    translation: "food",
    pronunciation: "pahg-kah-on",
    example: "Nangaon kami.",
    exampleTranslation: "We are eating.",
    date: "2025-04-11",
  },
  {
    id: "102",
    dialectId: "cebuano",
    word: "bugas",
    translation: "rice",
    pronunciation: "boo-gahs",
    example: "Nagluto kami og bugas.",
    exampleTranslation: "We cooked rice.",
    date: "2025-04-12",
  },
  {
    id: "103",
    dialectId: "cebuano",
    word: "isda",
    translation: "fish",
    pronunciation: "ees-dah",
    example: "Nagpalit kami og isda.",
    exampleTranslation: "We bought fish.",
    date: "2025-04-13",
  },
  {
    id: "104",
    dialectId: "cebuano",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Nagluto kami og karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-04-14",
  },
  {
    id: "105",
    dialectId: "cebuano",
    word: "utan",
    translation: "vegetable",
    pronunciation: "oo-tahn",
    example: "Nangaon kami og utan.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-04-15",
  },
  {
    id: "106",
    dialectId: "cebuano",
    word: "prutas",
    translation: "fruit",
    pronunciation: "proo-tahs",
    example: "Nangaon kami og prutas.",
    exampleTranslation: "We ate fruit.",
    date: "2025-04-16",
  },
  {
    id: "107",
    dialectId: "cebuano",
    word: "iro",
    translation: "dog",
    pronunciation: "ee-roh",
    example: "Naa mi iro.",
    exampleTranslation: "We have a dog.",
    date: "2025-04-17",
  },
  {
    id: "108",
    dialectId: "cebuano",
    word: "iring",
    translation: "cat",
    pronunciation: "ee-ring",
    example: "Naa mi iring.",
    exampleTranslation: "We have a cat.",
    date: "2025-04-18",
  },

  // --- ILOCANO (CONTINUED) ---
  {
    id: "111",
    dialectId: "ilocano",
    word: "kablaaw",
    translation: "hello",
    pronunciation: "kab-lah-ow",
    example: "Kablaaw!",
    exampleTranslation: "Hello!",
    date: "2025-04-19",
  },
  {
    id: "112",
    dialectId: "ilocano",
    word: "naimbag a bigat",
    translation: "good morning",
    pronunciation: "nah-eem-bahg ah bee-gaht",
    example: "Naimbag a bigat!",
    exampleTranslation: "Good morning!",
    date: "2025-04-20",
  },
  {
    id: "113",
    dialectId: "ilocano",
    word: "naimbag a malem",
    translation: "good afternoon",
    pronunciation: "nah-eem-bahg ah mah-lem",
    example: "Naimbag a malem!",
    exampleTranslation: "Good afternoon!",
    date: "2025-04-21",
  },
  {
    id: "114",
    dialectId: "ilocano",
    word: "naimbag a rabii",
    translation: "good evening",
    pronunciation: "nah-eem-bahg ah rah-bee",
    example: "Naimbag a rabii!",
    exampleTranslation: "Good evening!",
    date: "2025-04-22",
  },
  {
    id: "115",
    dialectId: "ilocano",
    word: "agyamanak",
    translation: "thank you",
    pronunciation: "ahg-yah-mah-nahk",
    example: "Agyamanak unay!",
    exampleTranslation: "Thank you very much!",
    date: "2025-04-23",
  },
  {
    id: "116",
    dialectId: "ilocano",
    word: "awan ania man",
    translation: "you're welcome",
    pronunciation: "ah-wahn ah-nee-ah mahn",
    example: "Awan ania man!",
    exampleTranslation: "You're welcome!",
    date: "2025-04-24",
  },
  {
    id: "117",
    dialectId: "ilocano",
    word: "wen",
    translation: "yes",
    pronunciation: "wen",
    example: "Wen, husto ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-04-25",
  },
  {
    id: "118",
    dialectId: "ilocano",
    word: "saan",
    translation: "no",
    pronunciation: "sah-ahn",
    example: "Saan, diak kayat.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-04-26",
  },
  {
    id: "119",
    dialectId: "ilocano",
    word: "pakiusap",
    translation: "please",
    pronunciation: "pah-kee-oo-sahp",
    example: "Pangaasi, tulungannak.",
    exampleTranslation: "Please, help me.",
    date: "2025-04-27",
  },
  {
    id: "120",
    dialectId: "ilocano",
    word: "pakawanennak",
    translation: "excuse me",
    pronunciation: "pah-kah-wah-nen-nahk",
    example: "Pakawanennak, sadino ti papananyo?",
    exampleTranslation: "Excuse me, where are you going?",
    date: "2025-04-28",
  },
  {
    id: "121",
    dialectId: "ilocano",
    word: "ania",
    translation: "what",
    pronunciation: "ah-nee-ah",
    example: "Ania daytoy?",
    exampleTranslation: "What is this?",
    date: "2025-04-29",
  },
  {
    id: "122",
    dialectId: "ilocano",
    word: "asino",
    translation: "who",
    pronunciation: "ah-see-no",
    example: "Asino ka?",
    exampleTranslation: "Who are you?",
    date: "2025-04-30",
  },
  {
    id: "123",
    dialectId: "ilocano",
    word: "sadino",
    translation: "where",
    pronunciation: "sah-dee-no",
    example: "Sadino ti naggapuam?",
    exampleTranslation: "Where are you from?",
    date: "2025-05-01",
  },
  {
    id: "124",
    dialectId: "ilocano",
    word: "kano",
    translation: "when",
    pronunciation: "kah-no",
    example: "Kaano ka sumangpet?",
    exampleTranslation: "When will you arrive?",
    date: "2025-05-02",
  },
  {
    id: "125",
    dialectId: "ilocano",
    word: "apay",
    translation: "why",
    pronunciation: "ah-pie",
    example: "Apay nga agsangsangitka?",
    exampleTranslation: "Why are you crying?",
    date: "2025-05-03",
  },
  {
    id: "126",
    dialectId: "ilocano",
    word: "kasano",
    translation: "how",
    pronunciation: "kah-sah-no",
    example: "Kasano daytoy?",
    exampleTranslation: "How is this?",
    date: "2025-05-04",
  },
  {
    id: "127",
    dialectId: "ilocano",
    word: "lallaki",
    translation: "man",
    pronunciation: "lahl-lah-kee",
    example: "Lallaki isuna.",
    exampleTranslation: "He is a man.",
    date: "2025-05-05",
  },
  {
    id: "128",
    dialectId: "ilocano",
    word: "babai",
    translation: "woman",
    pronunciation: "bah-bah-ee",
    example: "Babai isuna.",
    exampleTranslation: "She is a woman.",
    date: "2025-05-06",
  },
  {
    id: "129",
    dialectId: "ilocano",
    word: "ubing",
    translation: "child",
    pronunciation: "oo-bing",
    example: "Ubing pay isuna.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-05-07",
  },
  {
    id: "130",
    dialectId: "ilocano",
    word: "ama",
    translation: "father",
    pronunciation: "ah-mah",
    example: "Ama ko isuna.",
    exampleTranslation: "He is my father.",
    date: "2025-05-08",
  },
  {
    id: "131",
    dialectId: "ilocano",
    word: "ina",
    translation: "mother",
    pronunciation: "ee-nah",
    example: "Ina ko isuna.",
    exampleTranslation: "She is my mother.",
    date: "2025-05-09",
  },
  {
    id: "132",
    dialectId: "ilocano",
    word: "kabsat a lallaki",
    translation: "brother",
    pronunciation: "kahb-saht ah lahl-lah-kee",
    example: "Kabsat ko a lallaki isuna.",
    exampleTranslation: "He is my brother.",
    date: "2025-05-10",
  },
  {
    id: "133",
    dialectId: "ilocano",
    word: "kabsat a babai",
    translation: "sister",
    pronunciation: "kahb-saht ah bah-bah-ee",
    example: "Kabsat ko a babai isuna.",
    exampleTranslation: "She is my sister.",
    date: "2025-05-11",
  },
  {
    id: "134",
    dialectId: "ilocano",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilyak isuda.",
    exampleTranslation: "They are my family.",
    date: "2025-05-12",
  },
  {
    id: "135",
    dialectId: "ilocano",
    word: "gayem",
    translation: "friend",
    pronunciation: "gah-yem",
    example: "Gayem ko isuna.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-05-13",
  },
  {
    id: "136",
    dialectId: "ilocano",
    word: "balay",
    translation: "house",
    pronunciation: "bah-lie",
    example: "Balay ko daytoy.",
    exampleTranslation: "This is my house.",
    date: "2025-05-14",
  },
  {
    id: "137",
    dialectId: "ilocano",
    word: "eskuela",
    translation: "school",
    pronunciation: "es-kweh-lah",
    example: "Agbasbasaak iti eskuela.",
    exampleTranslation: "I study at school.",
    date: "2025-05-15",
  },
  {
    id: "138",
    dialectId: "ilocano",
    word: "simbaan",
    translation: "church",
    pronunciation: "seem-bah-ahn",
    example: "Napan kami idiay simbaan.",
    exampleTranslation: "We went to church.",
    date: "2025-05-16",
  },
  {
    id: "139",
    dialectId: "ilocano",
    word: "tiendaan",
    translation: "market",
    pronunciation: "tee-en-dah-ahn",
    example: "Gimmatang kami iti tiendaan.",
    exampleTranslation: "We shopped at the market.",
    date: "2025-05-17",
  },
  {
    id: "140",
    dialectId: "ilocano",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Nagna kami iti dalan.",
    exampleTranslation: "We walked on the road.",
    date: "2025-05-18",
  },
  {
    id: "141",
    dialectId: "ilocano",
    word: "baybay",
    translation: "sea",
    pronunciation: "bah-ee-bah-ee",
    example: "Naglangoy kami idiay baybay.",
    exampleTranslation: "We swam in the sea.",
    date: "2025-05-19",
  },
  {
    id: "142",
    dialectId: "ilocano",
    word: "bantay",
    translation: "mountain",
    pronunciation: "bahn-tie",
    example: "Simmang-at kami iti bantay.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-05-20",
  },
  {
    id: "143",
    dialectId: "ilocano",
    word: "karayan",
    translation: "river",
    pronunciation: "kah-rah-yahn",
    example: "Naglangoy kami idiay karayan.",
    exampleTranslation: "We swim in the river.",
    date: "2025-05-21",
  },
  {
    id: "144",
    dialectId: "ilocano",
    word: "init",
    translation: "sun",
    pronunciation: "ee-nit",
    example: "Napudot ti init.",
    exampleTranslation: "The sun is hot.",
    date: "2025-05-22",
  },
  {
    id: "145",
    dialectId: "ilocano",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Naraniag ti bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-05-23",
  },
  {
    id: "146",
    dialectId: "ilocano",
    word: "bituen",
    translation: "star",
    pronunciation: "bee-too-en",
    example: "Adu a bituen ti langit.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-05-24",
  },
  {
    id: "147",
    dialectId: "ilocano",
    word: "tudo",
    translation: "rain",
    pronunciation: "too-doh",
    example: "Nagtudo idi kalman.",
    exampleTranslation: "It rained yesterday.",
    date: "2025-05-25",
  },
  {
    id: "148",
    dialectId: "ilocano",
    word: "angin",
    translation: "wind",
    pronunciation: "ahn-gin",
    example: "Napigsa ti angin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-05-26",
  },
  {
    id: "149",
    dialectId: "ilocano",
    word: "apoy",
    translation: "fire",
    pronunciation: "ah-poy",
    example: "Napudot ti apoy.",
    exampleTranslation: "The fire is hot.",
    date: "2025-05-27",
  },
  {
    id: "150",
    dialectId: "ilocano",
    word: "danum",
    translation: "water",
    pronunciation: "dah-noom",
    example: "Nalamiis ti danum.",
    exampleTranslation: "The water is cold.",
    date: "2025-05-28",
  },
  {
    id: "151",
    dialectId: "ilocano",
    word: "makan",
    translation: "food",
    pronunciation: "mah-kahn",
    example: "Nangan kami.",
    exampleTranslation: "We are eating.",
    date: "2025-05-29",
  },
  {
    id: "152",
    dialectId: "ilocano",
    word: "bagas",
    translation: "rice",
    pronunciation: "bah-gahs",
    example: "Nagluto kami ti bagas.",
    exampleTranslation: "We cooked rice.",
    date: "2025-05-30",
  },
  {
    id: "153",
    dialectId: "ilocano",
    word: "ikan",
    translation: "fish",
    pronunciation: "ee-kahn",
    example: "Gimmatang kami ti ikan.",
    exampleTranslation: "We bought fish.",
    date: "2025-05-31",
  },
  {
    id: "154",
    dialectId: "ilocano",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Nagluto kami ti karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-06-01",
  },
  {
    id: "155",
    dialectId: "ilocano",
    word: "nateng",
    translation: "vegetable",
    pronunciation: "nah-teng",
    example: "Nangan kami ti nateng.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-06-02",
  },
  {
    id: "156",
    dialectId: "ilocano",
    word: "bunga",
    translation: "fruit",
    pronunciation: "boong-ah",
    example: "Nangan kami ti bunga.",
    exampleTranslation: "We ate fruit.",
    date: "2025-06-03",
  },
  {
    id: "157",
    dialectId: "ilocano",
    word: "aso",
    translation: "dog",
    pronunciation: "ah-so",
    example: "Adda aso mi.",
    exampleTranslation: "We have a dog.",
    date: "2025-06-04",
  },
  {
    id: "158",
    dialectId: "ilocano",
    word: "pusa",
    translation: "cat",
    pronunciation: "poo-sah",
    example: "Adda pusa mi.",
    exampleTranslation: "We have a cat.",
    date: "2025-06-05",
  },

  // --- HILIGAYNON (CONTINUED) ---
  {
    id: "161",
    dialectId: "hiligaynon",
    word: "kamusta",
    translation: "hello",
    pronunciation: "kah-mus-tah",
    example: "Kamusta ka?",
    exampleTranslation: "How are you?",
    date: "2025-06-06",
  },
  {
    id: "162",
    dialectId: "hiligaynon",
    word: "maayong aga",
    translation: "good morning",
    pronunciation: "mah-ah-yong ah-gah",
    example: "Maayong aga!",
    exampleTranslation: "Good morning!",
    date: "2025-06-07",
  },
  {
    id: "163",
    dialectId: "hiligaynon",
    word: "maayong hapon",
    translation: "good afternoon",
    pronunciation: "mah-ah-yong hah-pon",
    example: "Maayong hapon sa inyo!",
    exampleTranslation: "Good afternoon to you!",
    date: "2025-06-08",
  },
  {
    id: "164",
    dialectId: "hiligaynon",
    word: "maayong gabi-i",
    translation: "good evening",
    pronunciation: "mah-ah-yong gah-bee",
    example: "Maayong gabi-i!",
    exampleTranslation: "Good evening!",
    date: "2025-06-09",
  },
  {
    id: "165",
    dialectId: "hiligaynon",
    word: "maayong gab-i",
    translation: "good night",
    pronunciation: "mah-ah-yong gahb-ee",
    example: "Maayong gab-i!",
    exampleTranslation: "Good night!",
    date: "2025-06-10",
  },
  {
    id: "166",
    dialectId: "hiligaynon",
    word: "wala sang anuman",
    translation: "you're welcome",
    pronunciation: "wah-lah sang ah-noo-mahn",
    example: "Wala sang anuman!",
    exampleTranslation: "You're welcome!",
    date: "2025-06-11",
  },
  {
    id: "167",
    dialectId: "hiligaynon",
    word: "hoo",
    translation: "yes",
    pronunciation: "hoh",
    example: "Hoo, tama ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-06-12",
  },
  {
    id: "168",
    dialectId: "hiligaynon",
    word: "indi",
    translation: "no",
    pronunciation: "in-dee",
    example: "Indi, indi ko gusto.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-06-13",
  },
  {
    id: "169",
    dialectId: "hiligaynon",
    word: "palihog",
    translation: "please",
    pronunciation: "pah-lee-hog",
    example: "Palihog, buligi ako.",
    exampleTranslation: "Please, help me.",
    date: "2025-06-14",
  },
  {
    id: "170",
    dialectId: "hiligaynon",
    word: "pasensya",
    translation: "excuse me",
    pronunciation: "pah-sen-syah",
    example: "Pasensya, pwede ko maagi?",
    exampleTranslation: "Excuse me, can I pass?",
    date: "2025-06-15",
  },
  {
    id: "171",
    dialectId: "hiligaynon",
    word: "ano",
    translation: "what",
    pronunciation: "ah-no",
    example: "Ano ini?",
    exampleTranslation: "What is this?",
    date: "2025-06-16",
  },
  {
    id: "172",
    dialectId: "hiligaynon",
    word: "sino",
    translation: "who",
    pronunciation: "see-no",
    example: "Sino ka?",
    exampleTranslation: "Who are you?",
    date: "2025-06-17",
  },
  {
    id: "173",
    dialectId: "hiligaynon",
    word: "diin",
    translation: "where",
    pronunciation: "dee-in",
    example: "Diin ka naghalin?",
    exampleTranslation: "Where are you from?",
    date: "2025-06-18",
  },
  {
    id: "174",
    dialectId: "hiligaynon",
    word: "san-o",
    translation: "when",
    pronunciation: "sahn-oh",
    example: "San-o ka mag-abot?",
    exampleTranslation: "When will you arrive?",
    date: "2025-06-19",
  },
  {
    id: "175",
    dialectId: "hiligaynon",
    word: "ngaa",
    translation: "why",
    pronunciation: "ngah-ah",
    example: "Ngaa nagahibi ka?",
    exampleTranslation: "Why are you crying?",
    date: "2025-06-20",
  },
  {
    id: "176",
    dialectId: "hiligaynon",
    word: "paano",
    translation: "how",
    pronunciation: "pah-ah-no",
    example: "Paano ini?",
    exampleTranslation: "How is this?",
    date: "2025-06-21",
  },
  {
    id: "177",
    dialectId: "hiligaynon",
    word: "lalaki",
    translation: "man",
    pronunciation: "lah-lah-kee",
    example: "Lalaki siya.",
    exampleTranslation: "He is a man.",
    date: "2025-06-22",
  },
  {
    id: "178",
    dialectId: "hiligaynon",
    word: "babayi",
    translation: "woman",
    pronunciation: "bah-bah-yee",
    example: "Babayi siya.",
    exampleTranslation: "She is a woman.",
    date: "2025-06-23",
  },
  {
    id: "179",
    dialectId: "hiligaynon",
    word: "bata",
    translation: "child",
    pronunciation: "bah-tah",
    example: "Bata pa siya.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-06-24",
  },
  {
    id: "180",
    dialectId: "hiligaynon",
    word: "amay",
    translation: "father",
    pronunciation: "ah-mie",
    example: "Amay ko siya.",
    exampleTranslation: "He is my father.",
    date: "2025-06-25",
  },
  {
    id: "181",
    dialectId: "hiligaynon",
    word: "iloy",
    translation: "mother",
    pronunciation: "ee-loy",
    example: "Iloy ko siya.",
    exampleTranslation: "She is my mother.",
    date: "2025-06-26",
  },
  {
    id: "182",
    dialectId: "hiligaynon",
    word: "utod nga lalaki",
    translation: "brother",
    pronunciation: "oo-tod ngah lah-lah-kee",
    example: "Utod ko nga lalaki siya.",
    exampleTranslation: "He is my brother.",
    date: "2025-06-27",
  },
  {
    id: "183",
    dialectId: "hiligaynon",
    word: "utod nga babayi",
    translation: "sister",
    pronunciation: "oo-tod ngah bah-bah-yee",
    example: "Utod ko nga babayi siya.",
    exampleTranslation: "She is my sister.",
    date: "2025-06-28",
  },
  {
    id: "184",
    dialectId: "hiligaynon",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilya ko sila.",
    exampleTranslation: "They are my family.",
    date: "2025-06-29",
  },
  {
    id: "185",
    dialectId: "hiligaynon",
    word: "abyan",
    translation: "friend",
    pronunciation: "ahb-yahn",
    example: "Abyan ko siya.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-06-30",
  },
  {
    id: "186",
    dialectId: "hiligaynon",
    word: "balay",
    translation: "house",
    pronunciation: "bah-lie",
    example: "Akon ini balay.",
    exampleTranslation: "This is my house.",
    date: "2025-07-01",
  },
  {
    id: "187",
    dialectId: "hiligaynon",
    word: "eskwelahan",
    translation: "school",
    pronunciation: "es-kweh-lah-hahn",
    example: "Nag-eskwela ako sa eskwelahan.",
    exampleTranslation: "I study at school.",
    date: "2025-07-02",
  },
  {
    id: "188",
    dialectId: "hiligaynon",
    word: "simbahan",
    translation: "church",
    pronunciation: "seem-bah-hahn",
    example: "Nagsimba kami sa simbahan.",
    exampleTranslation: "We go to church.",
    date: "2025-07-03",
  },
  {
    id: "189",
    dialectId: "hiligaynon",
    word: "merkado",
    translation: "market",
    pronunciation: "mer-kah-doh",
    example: "Nagbakal kami sa merkado.",
    exampleTranslation: "We shop at the market.",
    date: "2025-07-04",
  },
  {
    id: "190",
    dialectId: "hiligaynon",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Naglakat kami sa dalan.",
    exampleTranslation: "We walk on the road.",
    date: "2025-07-05",
  },
  {
    id: "191",
    dialectId: "hiligaynon",
    word: "dagat",
    translation: "sea",
    pronunciation: "dah-gaht",
    example: "Nagpaligo kami sa dagat.",
    exampleTranslation: "We swim in the sea.",
    date: "2025-07-06",
  },
  {
    id: "192",
    dialectId: "hiligaynon",
    word: "bukid",
    translation: "mountain",
    pronunciation: "boo-keed",
    example: "Nagsaka kami sa bukid.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-07-07",
  },
  {
    id: "193",
    dialectId: "hiligaynon",
    word: "suba",
    translation: "river",
    pronunciation: "soo-bah",
    example: "Nagpaligo kami sa suba.",
    exampleTranslation: "We swim in the river.",
    date: "2025-07-08",
  },
  {
    id: "194",
    dialectId: "hiligaynon",
    word: "adlaw",
    translation: "sun",
    pronunciation: "ahd-lahw",
    example: "Mainit ang adlaw.",
    exampleTranslation: "The sun is hot.",
    date: "2025-07-09",
  },
  {
    id: "195",
    dialectId: "hiligaynon",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Masanag ang bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-07-10",
  },
  {
    id: "196",
    dialectId: "hiligaynon",
    word: "bitoon",
    translation: "star",
    pronunciation: "bee-toh-on",
    example: "Madamo nga bitoon sa langit.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-07-11",
  },
  {
    id: "197",
    dialectId: "hiligaynon",
    word: "ulan",
    translation: "rain",
    pronunciation: "oo-lahn",
    example: "Nag-ulan kahapon.",
    exampleTranslation: "It rained yesterday.",
    date: "2025-07-12",
  },
  {
    id: "198",
    dialectId: "hiligaynon",
    word: "hangin",
    translation: "wind",
    pronunciation: "hah-ngin",
    example: "Mabaskog ang hangin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-07-13",
  },
  {
    id: "199",
    dialectId: "hiligaynon",
    word: "kalayo",
    translation: "fire",
    pronunciation: "kah-lah-yo",
    example: "Mainit ang kalayo.",
    exampleTranslation: "The fire is hot.",
    date: "2025-07-14",
  },
  {
    id: "200",
    dialectId: "hiligaynon",
    word: "tubig",
    translation: "water",
    pronunciation: "too-big",
    example: "Mabugnaw ang tubig.",
    exampleTranslation: "The water is cold.",
    date: "2025-07-15",
  },
  {
    id: "201",
    dialectId: "hiligaynon",
    word: "kan-on",
    translation: "food",
    pronunciation: "kahn-on",
    example: "Nagkaon kami.",
    exampleTranslation: "We are eating.",
    date: "2025-07-16",
  },
  {
    id: "202",
    dialectId: "hiligaynon",
    word: "bugas",
    translation: "rice",
    pronunciation: "boo-gahs",
    example: "Nagluto kami sang bugas.",
    exampleTranslation: "We cooked rice.",
    date: "2025-07-17",
  },
  {
    id: "203",
    dialectId: "hiligaynon",
    word: "isdâ",
    translation: "fish",
    pronunciation: "ees-dah",
    example: "Nagbakal kami sang isdâ.",
    exampleTranslation: "We bought fish.",
    date: "2025-07-18",
  },
  {
    id: "204",
    dialectId: "hiligaynon",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Nagluto kami sang karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-07-19",
  },
  {
    id: "205",
    dialectId: "hiligaynon",
    word: "utan",
    translation: "vegetable",
    pronunciation: "oo-tahn",
    example: "Nagkaon kami sang utan.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-07-20",
  },
  {
    id: "206",
    dialectId: "hiligaynon",
    word: "prutas",
    translation: "fruit",
    pronunciation: "proo-tahs",
    example: "Nagkaon kami sang prutas.",
    exampleTranslation: "We ate fruit.",
    date: "2025-07-21",
  },
  {
    id: "207",
    dialectId: "hiligaynon",
    word: "ido",
    translation: "dog",
    pronunciation: "ee-doh",
    example: "May ido kami.",
    exampleTranslation: "We have a dog.",
    date: "2025-07-22",
  },
  {
    id: "208",
    dialectId: "hiligaynon",
    word: "kuring",
    translation: "cat",
    pronunciation: "koo-ring",
    example: "May kuring kami.",
    exampleTranslation: "We have a cat.",
    date: "2025-07-23",
  },

  // --- KAPAMPANGAN (CONTINUED) ---
  {
    id: "211",
    dialectId: "kapampangan",
    word: "kumusta",
    translation: "hello",
    pronunciation: "koo-mus-tah",
    example: "Kumusta ka?",
    exampleTranslation: "How are you?",
    date: "2025-07-24",
  },
  {
    id: "212",
    dialectId: "kapampangan",
    word: "mayap a abak",
    translation: "good morning",
    pronunciation: "mah-yahp ah ah-bahk",
    example: "Mayap a abak!",
    exampleTranslation: "Good morning!",
    date: "2025-07-25",
  },
  {
    id: "213",
    dialectId: "kapampangan",
    word: "mayap a gatpanapun",
    translation: "good afternoon",
    pronunciation: "mah-yahp ah gaht-pah-nah-poon",
    example: "Mayap a gatpanapun!",
    exampleTranslation: "Good afternoon!",
    date: "2025-07-26",
  },
  {
    id: "214",
    dialectId: "kapampangan",
    word: "mayap a bengi",
    translation: "good evening",
    pronunciation: "mah-yahp ah ben-gee",
    example: "Mayap a bengi!",
    exampleTranslation: "Good evening!",
    date: "2025-07-27",
  },
  {
    id: "215",
    dialectId: "kapampangan",
    word: "dakal a salamat",
    translation: "thank you",
    pronunciation: "dah-kahl ah sah-lah-maht",
    example: "Dakal a salamat!",
    exampleTranslation: "Thank you very much!",
    date: "2025-07-28",
  },
  {
    id: "216",
    dialectId: "kapampangan",
    word: "aliwa man",
    translation: "you're welcome",
    pronunciation: "ah-lee-wah mahn",
    example: "Aliwa man!",
    exampleTranslation: "You're welcome!",
    date: "2025-07-29",
  },
  {
    id: "217",
    dialectId: "kapampangan",
    word: "wa",
    translation: "yes",
    pronunciation: "wah",
    example: "Wa, tama ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-07-30",
  },
  {
    id: "218",
    dialectId: "kapampangan",
    word: "aliwa",
    translation: "no",
    pronunciation: "ah-lee-wah",
    example: "Aliwa, ali ku buri.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-07-31",
  },
  {
    id: "219",
    dialectId: "kapampangan",
    word: "pakisabi",
    translation: "please",
    pronunciation: "pah-kee-sah-bee",
    example: "Pakisabi, sopan mu ku.",
    exampleTranslation: "Please, help me.",
    date: "2025-08-01",
  },
  {
    id: "220",
    dialectId: "kapampangan",
    word: "pakikwan",
    translation: "excuse me",
    pronunciation: "pah-kee-kwahn",
    example: "Pakikwan, nukarin kayu munta?",
    exampleTranslation: "Excuse me, where are you going?",
    date: "2025-08-02",
  },
  {
    id: "221",
    dialectId: "kapampangan",
    word: "nanu",
    translation: "what",
    pronunciation: "nah-noo",
    example: "Nanu ini?",
    exampleTranslation: "What is this?",
    date: "2025-08-03",
  },
  {
    id: "222",
    dialectId: "kapampangan",
    word: "ninu",
    translation: "who",
    pronunciation: "nee-noo",
    example: "Ninu ka?",
    exampleTranslation: "Who are you?",
    date: "2025-08-04",
  },
  {
    id: "223",
    dialectId: "kapampangan",
    word: "nokarin",
    translation: "where",
    pronunciation: "no-kah-rin",
    example: "Nokarin ka ibat?",
    exampleTranslation: "Where are you from?",
    date: "2025-08-05",
  },
  {
    id: "224",
    dialectId: "kapampangan",
    word: "kapilan",
    translation: "when",
    pronunciation: "kah-pee-lahn",
    example: "Kapilan ka datang?",
    exampleTranslation: "When will you arrive?",
    date: "2025-08-06",
  },
  {
    id: "225",
    dialectId: "kapampangan",
    word: "bakit",
    translation: "why",
    pronunciation: "bah-kit",
    example: "Bakit ka kikiak?",
    exampleTranslation: "Why are you crying?",
    date: "2025-08-07",
  },
  {
    id: "226",
    dialectId: "kapampangan",
    word: "makananu",
    translation: "how",
    pronunciation: "mah-kah-nah-noo",
    example: "Makananu ini?",
    exampleTranslation: "How is this?",
    date: "2025-08-08",
  },
  {
    id: "227",
    dialectId: "kapampangan",
    word: "lalaki",
    translation: "man",
    pronunciation: "lah-lah-kee",
    example: "Lalaki ya.",
    exampleTranslation: "He is a man.",
    date: "2025-08-09",
  },
  {
    id: "228",
    dialectId: "kapampangan",
    word: "babai",
    translation: "woman",
    pronunciation: "bah-bah-ee",
    example: "Babai ya.",
    exampleTranslation: "She is a woman.",
    date: "2025-08-10",
  },
  {
    id: "229",
    dialectId: "kapampangan",
    word: "anac",
    translation: "child",
    pronunciation: "ah-nahts",
    example: "Anac ya pa.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-08-11",
  },
  {
    id: "230",
    dialectId: "kapampangan",
    word: "tatang",
    translation: "father",
    pronunciation: "tah-tahng",
    example: "Tatang ke.",
    exampleTranslation: "He is my father.",
    date: "2025-08-12",
  },
  {
    id: "231",
    dialectId: "kapampangan",
    word: "indung",
    translation: "mother",
    pronunciation: "in-doong",
    example: "Indung ke.",
    exampleTranslation: "She is my mother.",
    date: "2025-08-13",
  },
  {
    id: "232",
    dialectId: "kapampangan",
    word: "kapatad a lalaki",
    translation: "brother",
    pronunciation: "kah-pah-tahd ah lah-lah-kee",
    example: "Kapatad ke a lalaki.",
    exampleTranslation: "He is my brother.",
    date: "2025-08-14",
  },
  {
    id: "233",
    dialectId: "kapampangan",
    word: "kapatad a babai",
    translation: "sister",
    pronunciation: "kah-pah-tahd ah bah-bah-ee",
    example: "Kapatad ke a babai.",
    exampleTranslation: "She is my sister.",
    date: "2025-08-15",
  },
  {
    id: "234",
    dialectId: "kapampangan",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilya ku la.",
    exampleTranslation: "They are my family.",
    date: "2025-08-16",
  },
  {
    id: "235",
    dialectId: "kapampangan",
    word: "kaluguran",
    translation: "friend",
    pronunciation: "kah-loo-goo-rahn",
    example: "Kaluguran ke.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-08-17",
  },
  {
    id: "236",
    dialectId: "kapampangan",
    word: "bale",
    translation: "house",
    pronunciation: "bah-leh",
    example: "Bale ku ini.",
    exampleTranslation: "This is my house.",
    date: "2025-08-18",
  },
  {
    id: "237",
    dialectId: "kapampangan",
    word: "eskwela",
    translation: "school",
    pronunciation: "es-kweh-lah",
    example: "Mig-aral ku king eskwela.",
    exampleTranslation: "I study at school.",
    date: "2025-08-19",
  },
  {
    id: "238",
    dialectId: "kapampangan",
    word: "pisamban",
    translation: "church",
    pronunciation: "pee-sahm-bahn",
    example: "Menyamba kami king pisamban.",
    exampleTranslation: "We went to church.",
    date: "2025-08-20",
  },
  {
    id: "239",
    dialectId: "kapampangan",
    word: "tiyange",
    translation: "market",
    pronunciation: "tee-yahn-geh",
    example: "Simali kami king tiyange.",
    exampleTranslation: "We shopped at the market.",
    date: "2025-08-21",
  },
  {
    id: "240",
    dialectId: "kapampangan",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Linakad kami king dalan.",
    exampleTranslation: "We walked on the road.",
    date: "2025-08-22",
  },
  {
    id: "241",
    dialectId: "kapampangan",
    word: "dagat",
    translation: "sea",
    pronunciation: "dah-gaht",
    example: "Kinawe kami king dagat.",
    exampleTranslation: "We swam in the sea.",
    date: "2025-08-23",
  },
  {
    id: "242",
    dialectId: "kapampangan",
    word: "bunduk",
    translation: "mountain",
    pronunciation: "boon-dook",
    example: "Pemanik kami king bunduk.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-08-24",
  },
  {
    id: "243",
    dialectId: "kapampangan",
    word: "ilug",
    translation: "river",
    pronunciation: "ee-loog",
    example: "Kinawe kami king ilug.",
    exampleTranslation: "We swam in the river.",
    date: "2025-08-25",
  },
  {
    id: "244",
    dialectId: "kapampangan",
    word: "aldo",
    translation: "sun",
    pronunciation: "ahl-doh",
    example: "Mapali ing aldo.",
    exampleTranslation: "The sun is hot.",
    date: "2025-08-26",
  },
  {
    id: "245",
    dialectId: "kapampangan",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Masala ing bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-08-27",
  },
  {
    id: "246",
    dialectId: "kapampangan",
    word: "bituin",
    translation: "star",
    pronunciation: "bee-too-in",
    example: "Dakal a bituin king banwa.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-08-28",
  },
  {
    id: "247",
    dialectId: "kapampangan",
    word: "uran",
    translation: "rain",
    pronunciation: "oo-rahn",
    example: "Memuran napun.",
    exampleTranslation: "It rained yesterday.",
    date: "2025-08-29",
  },
  {
    id: "248",
    dialectId: "kapampangan",
    word: "angin",
    translation: "wind",
    pronunciation: "ahn-gin",
    example: "Masikan ing angin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-08-30",
  },
  {
    id: "249",
    dialectId: "kapampangan",
    word: "apuy",
    translation: "fire",
    pronunciation: "ah-poo-ee",
    example: "Mapali ing apuy.",
    exampleTranslation: "The fire is hot.",
    date: "2025-08-31",
  },
  {
    id: "250",
    dialectId: "kapampangan",
    word: "danum",
    translation: "water",
    pronunciation: "dah-noom",
    example: "Marimla ing danum.",
    exampleTranslation: "The water is cold.",
    date: "2025-09-01",
  },
  {
    id: "251",
    dialectId: "kapampangan",
    word: "pamangan",
    translation: "food",
    pronunciation: "pah-mahn-gahn",
    example: "Mengan kami.",
    exampleTranslation: "We ate.",
    date: "2025-09-02",
  },
  {
    id: "252",
    dialectId: "kapampangan",
    word: "nasi",
    translation: "rice",
    pronunciation: "nah-see",
    example: "Melutu kaming nasi.",
    exampleTranslation: "We cooked rice.",
    date: "2025-09-03",
  },
  {
    id: "253",
    dialectId: "kapampangan",
    word: "asan",
    translation: "fish",
    pronunciation: "ah-sahn",
    example: "Simali kaming asan.",
    exampleTranslation: "We bought fish.",
    date: "2025-09-04",
  },
  {
    id: "254",
    dialectId: "kapampangan",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Melutu kaming karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-09-05",
  },
  {
    id: "255",
    dialectId: "kapampangan",
    word: "gule",
    translation: "vegetable",
    pronunciation: "goo-leh",
    example: "Mengan kaming gule.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-09-06",
  },
  {
    id: "256",
    dialectId: "kapampangan",
    word: "prutas",
    translation: "fruit",
    pronunciation: "proo-tahs",
    example: "Mengan kaming prutas.",
    exampleTranslation: "We ate fruit.",
    date: "2025-09-07",
  },
  {
    id: "257",
    dialectId: "kapampangan",
    word: "asu",
    translation: "dog",
    pronunciation: "ah-soo",
    example: "Atin kaming asu.",
    exampleTranslation: "We have a dog.",
    date: "2025-09-08",
  },
  {
    id: "258",
    dialectId: "kapampangan",
    word: "pusa",
    translation: "cat",
    pronunciation: "poo-sah",
    example: "Atin kaming pusa.",
    exampleTranslation: "We have a cat.",
    date: "2025-09-09",
  },

  // --- WARAY (CONTINUED) ---
  {
    id: "259",
    dialectId: "waray",
    word: "kumusta",
    translation: "hello",
    pronunciation: "koo-mus-tah",
    example: "Kumusta ka?",
    exampleTranslation: "How are you?",
    date: "2025-09-10",
  },
  {
    id: "260",
    dialectId: "waray",
    word: "maupay nga aga",
    translation: "good morning",
    pronunciation: "mah-oo-pie ngah ah-gah",
    example: "Maupay nga aga!",
    exampleTranslation: "Good morning!",
    date: "2025-09-11",
  },
  {
    id: "261",
    dialectId: "waray",
    word: "maupay nga kulop",
    translation: "good afternoon",
    pronunciation: "mah-oo-pie ngah koo-lop",
    example: "Maupay nga kulop!",
    exampleTranslation: "Good afternoon!",
    date: "2025-09-12",
  },
  {
    id: "262",
    dialectId: "waray",
    word: "maupay nga gab-i",
    translation: "good evening",
    pronunciation: "mah-oo-pie ngah gah-bee",
    example: "Maupay nga gab-i!",
    exampleTranslation: "Good evening!",
    date: "2025-09-13",
  },
  {
    id: "263",
    dialectId: "waray",
    word: "maupay nga gab-i",
    translation: "good night",
    pronunciation: "mah-oo-pie ngah gah-bee",
    example: "Maupay nga gab-i!",
    exampleTranslation: "Good night!",
    date: "2025-09-14",
  },
  {
    id: "264",
    dialectId: "waray",
    word: "salamat",
    translation: "thank you",
    pronunciation: "sah-lah-maht",
    example: "Salamat hin damo!",
    exampleTranslation: "Thank you very much!",
    date: "2025-09-15",
  },
  {
    id: "265",
    dialectId: "waray",
    word: "waray sapayan",
    translation: "you're welcome",
    pronunciation: "wah-rie sah-pah-yahn",
    example: "Waray sapayan!",
    exampleTranslation: "You're welcome!",
    date: "2025-09-16",
  },
  {
    id: "266",
    dialectId: "waray",
    word: "oo",
    translation: "yes",
    pronunciation: "oh-oh",
    example: "Oo, tama ka.",
    exampleTranslation: "Yes, you're right.",
    date: "2025-09-17",
  },
  {
    id: "267",
    dialectId: "waray",
    word: "diri",
    translation: "no",
    pronunciation: "dee-ree",
    example: "Diri, diri ko gusto.",
    exampleTranslation: "No, I don't want to.",
    date: "2025-09-18",
  },
  {
    id: "268",
    dialectId: "waray",
    word: "alayon",
    translation: "please",
    pronunciation: "ah-lah-yon",
    example: "Alayon, buligi ako.",
    exampleTranslation: "Please, help me.",
    date: "2025-09-19",
  },
  {
    id: "269",
    dialectId: "waray",
    word: "pasayloa ako",
    translation: "excuse me",
    pronunciation: "pah-sah-ylo-ah ah-koh",
    example: "Pasayloa ako, diin kamo makadto?",
    exampleTranslation: "Excuse me, where are you going?",
    date: "2025-09-20",
  },
  {
    id: "270",
    dialectId: "waray",
    word: "pasaylo-a ako",
    translation: "sorry",
    pronunciation: "pah-sah-ylo-ah ah-koh",
    example: "Pasaylo-a ako!",
    exampleTranslation: "I'm sorry!",
    date: "2025-09-21",
  },
  {
    id: "271",
    dialectId: "waray",
    word: "ano",
    translation: "what",
    pronunciation: "ah-noh",
    example: "Ano ini?",
    exampleTranslation: "What is this?",
    date: "2025-09-22",
  },
  {
    id: "272",
    dialectId: "waray",
    word: "hin-o",
    translation: "who",
    pronunciation: "hin-oh",
    example: "Hin-o ka?",
    exampleTranslation: "Who are you?",
    date: "2025-09-23",
  },
  {
    id: "273",
    dialectId: "waray",
    word: "hain",
    translation: "where",
    pronunciation: "hah-in",
    example: "Diin ka tikang?",
    exampleTranslation: "Where are you from?",
    date: "2025-09-24",
  },
  {
    id: "274",
    dialectId: "waray",
    word: "kan-o",
    translation: "when",
    pronunciation: "kah-noh",
    example: "Kan-o ka maabot?",
    exampleTranslation: "When will you arrive?",
    date: "2025-09-25",
  },
  {
    id: "275",
    dialectId: "waray",
    word: "kay ano",
    translation: "why",
    pronunciation: "kah-ee ah-noh",
    example: "Kay ano nagtatangis ka?",
    exampleTranslation: "Why are you crying?",
    date: "2025-09-26",
  },
  {
    id: "276",
    dialectId: "waray",
    word: "paonan-o",
    translation: "how",
    pronunciation: "pah-oh-nahn-oh",
    example: "Paonan-o ini?",
    exampleTranslation: "How is this?",
    date: "2025-09-27",
  },
  {
    id: "277",
    dialectId: "waray",
    word: "lalaki",
    translation: "man",
    pronunciation: "lah-lah-kee",
    example: "Lalaki hiya.",
    exampleTranslation: "He is a man.",
    date: "2025-09-28",
  },
  {
    id: "278",
    dialectId: "waray",
    word: "babaye",
    translation: "woman",
    pronunciation: "bah-bah-yeh",
    example: "Babaye hiya.",
    exampleTranslation: "She is a woman.",
    date: "2025-09-29",
  },
  {
    id: "279",
    dialectId: "waray",
    word: "bata",
    translation: "child",
    pronunciation: "bah-tah",
    example: "Bata pa hiya.",
    exampleTranslation: "He/She is still a child.",
    date: "2025-09-30",
  },
  {
    id: "280",
    dialectId: "waray",
    word: "amay",
    translation: "father",
    pronunciation: "ah-mah-ee",
    example: "Amay ko hiya.",
    exampleTranslation: "He is my father.",
    date: "2025-10-01",
  },
  {
    id: "281",
    dialectId: "waray",
    word: "iroy",
    translation: "mother",
    pronunciation: "ee-roy",
    example: "Iroy ko hiya.",
    exampleTranslation: "She is my mother.",
    date: "2025-10-02",
  },
  {
    id: "282",
    dialectId: "waray",
    word: "bugto nga lalaki",
    translation: "brother",
    pronunciation: "boog-toh ngah lah-lah-kee",
    example: "Bugto ko nga lalaki hiya.",
    exampleTranslation: "He is my brother.",
    date: "2025-10-03",
  },
  {
    id: "283",
    dialectId: "waray",
    word: "bugto nga babaye",
    translation: "sister",
    pronunciation: "boog-toh ngah bah-bah-yeh",
    example: "Bugto ko nga babaye hiya.",
    exampleTranslation: "She is my sister.",
    date: "2025-10-04",
  },
  {
    id: "284",
    dialectId: "waray",
    word: "pamilya",
    translation: "family",
    pronunciation: "pah-meel-yah",
    example: "Pamilya ko hira.",
    exampleTranslation: "They are my family.",
    date: "2025-10-05",
  },
  {
    id: "285",
    dialectId: "waray",
    word: "sangkay",
    translation: "friend",
    pronunciation: "sahng-kah-ee",
    example: "Sangkay ko hiya.",
    exampleTranslation: "He/She is my friend.",
    date: "2025-10-06",
  },
  {
    id: "286",
    dialectId: "waray",
    word: "balay",
    translation: "house",
    pronunciation: "bah-lah-ee",
    example: "Akon ini balay.",
    exampleTranslation: "This is my house.",
    date: "2025-10-07",
  },
  {
    id: "287",
    dialectId: "waray",
    word: "eskwelahan",
    translation: "school",
    pronunciation: "es-kweh-lah-hahn",
    example: "Nag-eskwela ako.",
    exampleTranslation: "I study at school.",
    date: "2025-10-08",
  },
  {
    id: "288",
    dialectId: "waray",
    word: "simbahan",
    translation: "church",
    pronunciation: "sim-bah-hahn",
    example: "Nagsimba kami.",
    exampleTranslation: "We went to church.",
    date: "2025-10-09",
  },
  {
    id: "289",
    dialectId: "waray",
    word: "tiyange",
    translation: "market",
    pronunciation: "tee-yahn-geh",
    example: "Namalit kami ha tiyange.",
    exampleTranslation: "We shop at the market.",
    date: "2025-10-10",
  },
  {
    id: "290",
    dialectId: "waray",
    word: "dalan",
    translation: "road",
    pronunciation: "dah-lahn",
    example: "Naglakat kami ha dalan.",
    exampleTranslation: "We walk on the road.",
    date: "2025-10-11",
  },
  {
    id: "291",
    dialectId: "waray",
    word: "dagat",
    translation: "sea",
    pronunciation: "dah-gaht",
    example: "Nagkarigo kami ha dagat.",
    exampleTranslation: "We swim in the sea.",
    date: "2025-10-12",
  },
  {
    id: "292",
    dialectId: "waray",
    word: "bukid",
    translation: "mountain",
    pronunciation: "boo-kid",
    example: "Sinaka kami ha bukid.",
    exampleTranslation: "We climbed the mountain.",
    date: "2025-10-13",
  },
  {
    id: "293",
    dialectId: "waray",
    word: "suba",
    translation: "river",
    pronunciation: "soo-bah",
    example: "Nagkarigo kami ha suba.",
    exampleTranslation: "We swim in the river.",
    date: "2025-10-14",
  },
  {
    id: "294",
    dialectId: "waray",
    word: "adlaw",
    translation: "sun",
    pronunciation: "ahd-lah-oo",
    example: "Mainit an adlaw.",
    exampleTranslation: "The sun is hot.",
    date: "2025-10-15",
  },
  {
    id: "295",
    dialectId: "waray",
    word: "bulan",
    translation: "moon",
    pronunciation: "boo-lahn",
    example: "Malamrag an bulan.",
    exampleTranslation: "The moon is bright.",
    date: "2025-10-16",
  },
  {
    id: "296",
    dialectId: "waray",
    word: "bituon",
    translation: "star",
    pronunciation: "bee-too-on",
    example: "Damo nga bituon ha langit.",
    exampleTranslation: "Many stars in the sky.",
    date: "2025-10-17",
  },
  {
    id: "297",
    dialectId: "waray",
    word: "uran",
    translation: "rain",
    pronunciation: "oo-rahn",
    example: "Nag-uran kakulop.",
    exampleTranslation: "It rained yesterday.",
    date: "2025-10-18",
  },
  {
    id: "298",
    dialectId: "waray",
    word: "hangin",
    translation: "wind",
    pronunciation: "hahn-gin",
    example: "Makusog an hangin.",
    exampleTranslation: "The wind is strong.",
    date: "2025-10-19",
  },
  {
    id: "299",
    dialectId: "waray",
    word: "kalayo",
    translation: "fire",
    pronunciation: "kah-lah-yoh",
    example: "Mainit an kalayo.",
    exampleTranslation: "The fire is hot.",
    date: "2025-10-20",
  },
  {
    id: "300",
    dialectId: "waray",
    word: "tubig",
    translation: "water",
    pronunciation: "too-big",
    example: "Mahagkot an tubig.",
    exampleTranslation: "The water is cold.",
    date: "2025-10-21",
  },
  {
    id: "301",
    dialectId: "waray",
    word: "pagkaon",
    translation: "food",
    pronunciation: "pahg-kah-on",
    example: "Nangaon kami.",
    exampleTranslation: "We are eating.",
    date: "2025-10-22",
  },
  {
    id: "302",
    dialectId: "waray",
    word: "bugas",
    translation: "rice",
    pronunciation: "boo-gahs",
    example: "Naglung-ag kami hin bugas.",
    exampleTranslation: "We cooked rice.",
    date: "2025-10-23",
  },
  {
    id: "303",
    dialectId: "waray",
    word: "isda",
    translation: "fish",
    pronunciation: "ees-dah",
    example: "Namalit kami hin isda.",
    exampleTranslation: "We bought fish.",
    date: "2025-10-24",
  },
  {
    id: "304",
    dialectId: "waray",
    word: "karne",
    translation: "meat",
    pronunciation: "kar-neh",
    example: "Nagluto kami hin karne.",
    exampleTranslation: "We cooked meat.",
    date: "2025-10-25",
  },
  {
    id: "305",
    dialectId: "waray",
    word: "utan",
    translation: "vegetable",
    pronunciation: "oo-tahn",
    example: "Nangaon kami hin utan.",
    exampleTranslation: "We ate vegetables.",
    date: "2025-10-26",
  },
  {
    id: "306",
    dialectId: "waray",
    word: "prutas",
    translation: "fruit",
    pronunciation: "proo-tahs",
    example: "Nangaon kami hin prutas.",
    exampleTranslation: "We ate fruit.",
    date: "2025-10-27",
  },
  {
    id: "307",
    dialectId: "waray",
    word: "ayam",
    translation: "dog",
    pronunciation: "ah-yahm",
    example: "May ayam kami.",
    exampleTranslation: "We have a dog.",
    date: "2025-10-28",
  },
  {
    id: "308",
    dialectId: "waray",
    word: "iring",
    translation: "cat",
    pronunciation: "ee-ring",
    example: "May iring kami.",
    exampleTranslation: "We have a cat.",
    date: "2025-10-29",
  },
]

// Get word of the day based on current date
export function getWordOfTheDay(dialectId?: string): Word {
  const today = new Date()
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000)

  // If dialectId is provided, filter words for that dialect
  const availableWords = dialectId ? wordsDatabase.filter((w) => w.dialectId === dialectId) : wordsDatabase

  const wordIndex = dayOfYear % availableWords.length
  return availableWords[wordIndex]
}

// Get dialect by ID
export function getDialectById(id: string): Dialect | undefined {
  return dialects.find((d) => d.id === id)
}

// Get words by dialect
export function getWordsByDialect(dialectId: string): Word[] {
  return wordsDatabase.filter((w) => w.dialectId === dialectId)
}

export function getWordById(id: string): Word | undefined {
  return wordsDatabase.find((w) => w.id === id)
}
